### PR TITLE
Remove non-ocaml stuff

### PR DESCRIPTION
**Pull request by pm5**

### CODE REVIEW

**Comment by pbiggar** [comment]
Looks good! Thanks!

I don't think this updates the circleci.yml, which I think we should do when merging.

I just enabled CircleCI for forks so you should be able to get CI results on the next push.

**Comment by pm5** [comment]
Thanks.  I just pushed a version with updates on CI.

**Comment by pm5** [comment]
Still need to move /native/src to /src.  And we should probably also rename the package to tablecloth-base, no?  I do hope we can have for example tablecloth-stdlib someday.

**Comment by pbiggar** [comment]
> And we should probably also rename the package to tablecloth-base, no? I do hope we can have for example tablecloth-stdlib someday.

That's a good idea. You mean just the package right, not the repo?

**Comment by pbiggar** [comment]
~(Assuming you wanted a review here and were ready to merge, apologies if I misunderstood)~

edit: nvm, i see you're still moving to `src`. Code so far is all good, I'd be happy to merge now.

**Comment by pm5** [comment]
Let's leave the change of package name to tablecloth-base to another PR.  I think this looks good now.

**Comment by pbiggar** [comment]
Amazing, thanks!

**Pull request merged**
