### PR TITLE
Update ocaml support

### LINKED ISSUE #3: Update versions of ocaml supported
Need to update the Makefile, opam file and .circleci/config.yml to update the versions of Base and OCaml supported

### PR DESCRIPTION
**Pull request by pm5**
Add OCaml 4.13 and 4.14.  Fix #3

### CODE REVIEW

**Comment by pm5** [comment]
I guess since we will generate doc in tablecloth repo we don't need odoc here anymore.

**Review by pbiggar — COMMENTED** [review]
I think it would be worth keeping odoc as we're going to stop using it in the tablecloth repo, but would like to ensure it works so that docs.ocaml.com for the package keeps working.

**Comment by pbiggar** [comment]
Are you planning to add OCaml 5? I'm not sure the status of it

**Comment by pm5** [comment]
I haven't tested OCaml 5 yet.  It's still in beta release at the moment though.

**Comment by pm5** [comment]
Added odoc back and slightly bumped dune version.  I think this ready for merge.  Would love to see dune >= 3.0 but that probably belongs to another MR.

**Pull request merged**
